/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qatask;

import retrofit2.*;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;
import qatask.Factories.RetrofitServiceFactory;
import qatask.Services.JsonPlaceholderService;
import qatask.Utility.ConfigurationManager;
import qatask.Models.Post;

public class App {
    public static void main(String[] args) {
        String propertyFile = "./app/src/main/resources/config.properties";
        String baseUrl;
        try {
            ConfigurationManager config = new ConfigurationManager(propertyFile);
            baseUrl = config.getProperty("base.url");
        } catch (FileNotFoundException e) {
            System.out.println(e.getMessage());
            return;
        } catch (IOException e) {
            System.out.println(e.getMessage());
            return;
        }
        RetrofitServiceFactory factory = new RetrofitServiceFactory(baseUrl);
        JsonPlaceholderService service = factory.create(JsonPlaceholderService.class);
        Call<List<Post>> call = service.getPosts();
        Response<List<Post>> response;
        try {
            response = call.execute();
        } catch (IOException e) {
            System.out.println(e.getMessage());
            return;
        }
        if (response.isSuccessful()) {
            for (Post post : response.body()) {
                System.out.println(post.toString());
            }
        }
    }
}
